### ISSUE TITLE
Build dll with hand_tracking_test fail

### ISSUE THREAD

**Issue by MollyTing** [HW140701/Google_Mediapipe_Hand_Tracking_dll#2]
Hi,
I used the BUILD in hand_tracking_test to build the .dll,
but I got the wrong messenger,

In file included from mediapipe/examples/desktop/hand_tracking_test/hand_tracking_api.cpp:2:
mediapipe/examples/desktop/hand_tracking_test/hand_tracking_detect.h:14:10: fatal error: mediapipe/framework/port/parse_text_proto.h: No such file or directory
 #include "mediapipe/framework/port/parse_text_proto.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Target //mediapipe/examples/desktop/hand_tracking_test:Mediapipe_Hand_Tracking failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.827s, Critical Path: 0.48s
INFO: 3 processes: 3 internal.
FAILED: Build did NOT complete successfully

Could you provide how can I build the .dll ?
Thank you.

**Comment by HW140701** [comment]
My suggestion is to first compile the official repository example, such as hello world, handtracking, and then compile this repository after successful compilation

**Comment by MollyTing** [comment]
Thank you for your reply.
I have build the example - hello world, handtracking.
It can run the application hand tracking successfully.

Then move the folder - dll/hand_tracking_test to mediapipe/mediapipe/example/desktop/hand_trakcing_test.
And run 
"bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hand_tracking_test:Mediapipe_Hand_Tracking".
The above problem still exists.
Should I need to update any code in BUILD ?

**Comment by HW140701** [comment]
I use this command:

bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="D:\\Anaconda\\python.exe" mediapipe/examples/desktop/hand_tracking_test:Mediapipe_Hand_Tracking --verbose_failures

, and my operating system is windows

**Comment by MollyTing** [comment]
OK, I build it successfully !!!
I think I used the wrong command to run.

Is the .dll file in the folder - bazel-bin/mediapipe/examples/desktop/hand_tracking/ ?

If I update the API,  
I only need to copy the .dll file and use the original mediapipe release file - hand_tracking_desktop_live.pbtxt ?

**Comment by HW140701** [comment]
1. The Mediapipe_Hand_Tracking.dll is in the bazel-bin/mediapipe/examples/desktop/hand_tracking_test/ dir.
2. yeap, you should use the origin file hand_tracking_desktop_live.pbtxt, and you had better copy the all of mediapipe model file to the work directory, you can see the dll use example .

**Comment by MollyTing** [comment]
Did you try it on Linux ?
I succeeded build it on windows system.
But I fail build it on linux.
I use the command "bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="/usr/bin/python3" mediapipe/examples/desktop/hand_tracking_test:Mediapipe_Hand_Tracking --verbose_failures"

The following error occurred :

ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/737ae9b4687d5b830abdb8407d25fe28/external/org_tensorflow/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "/root/.cache/bazel/_bazel_root/737ae9b4687d5b830abdb8407d25fe28/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "/root/.cache/bazel/_bazel_root/737ae9b4687d5b830abdb8407d25fe28/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='/usr/bin/python/' is not executable. Is it the python binary?
ERROR: Analysis of target '//mediapipe/examples/desktop/hand_tracking_test:Mediapipe_Hand_Tracking' failed; build aborted: Configuration Error: --define PYTHON_BIN_PATH='/usr/bin/python/' is not executable. Is it the python binary?
INFO: Elapsed time: 0.995s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (16 packages loaded, 11 targets configured)

It seems cannot find the python,  but I can't solve it.

**Comment by MollyTing** [comment]
Sorry for asking a very simple question.
I gave the wrong path for PYTHON_BIN_PATH (/usr/bin/python).
But it happen the same problem with the first question -
mediapipe/examples/desktop/hand_tracking_test/hand_tracking_detect.h:14:10: fatal error: mediapipe/framework/port/parse_text_proto.h: No such file or directory
 #include "mediapipe/framework/port/parse_text_proto.h"
I think I need to know how to solve it correctly.
Thank you for your reply.

**Comment by HW140701** [comment]
This question is puzzling.
Please make sure you have executed this command under the mediapipe repository path.

**Comment by MollyTing** [comment]
Yes,
I run the command  in the <root/mediepipe>
and the command is 
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="/usr/bin/python3" mediapipe/examples/desktop/hand_tracking_test:Mediapipe_Hand_Tracking --verbose_failures

but I add the deps "//mediapipe/examples/desktop:simple_run_graph_main" in hand_tracking_test/BUILD line 31, before the "//mediapipe/graphs/hand_tracking:desktop_tflite_calculators",

It build successfully.
I'm not sure if this is correct ?

**Comment by HW140701** [comment]
if you can compile success ,may be correctly.
run the use example to test.

**Comment by MollyTing** [comment]
When I run the example to test, 
It will fail in hand_tracking_detect.cpp line 252,
camera_frame.copyTo(input_frame_mat);

and if I delete the line 252, it will fail in line 268,
if (!m_pPoller->Next(&packet))
    return absl::OkStatus();

Do you have any idea?

**Comment by HW140701** [comment]
you need include and link opencv.

**Comment by MollyTing** [comment]
I add include in hand_tracking_detect.cpp
#include "opencv2/opencv.hpp" 
and check the opencv link path in mediapipe/third_party/opencv_<platform>.BUILD
But it seems not work.

Should I update the hand_tracking_test/BUILD file ?

**Comment by HW140701** [comment]
if you include opencv  , camera_frame.copyTo(input_frame_mat) maybe not fail.

**Comment by MollyTing** [comment]
It can build the .dll successfully. 
But run the main.cpp will error. 
Check the code interrupt happen in camera_frame.copyTo(input_frame_mat).
I have include and link the opencv.
Thanks for all your answers.
I will keep trying until I succeed.

**Comment by HW140701** [comment]
I suggest you write an Opencv test program to test this problem.

**Comment by MollyTing** [comment]
OK, I'll try it.
Thank you.

**Comment by HW140701** [comment]
Good lucky!
Please close this issue.

**Comment by HW140701** [comment]
> Before this can be close exactly, I have ready most of the discussion and you help them to be success kindly. I have complete the action to build execution file, such as HelloWorld, and handtracking are runing through very well.
> 
> I would like to write down most of my material and build information as follow. **0. build command** bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:\Python37\python.exe" mediapipe/examples/desktop/hand_tracking_test:Mediapipe_Hand_Tracking --verbose_failures
> 
> **1.The error msg after the building** _D:/_longgoodprojects/mediapipe/mediapipe/examples/desktop/hand_tracking_test/BUILD:27:10: Compiling mediapipe/examples/desktop/hand_tracking_test/hand_tracking_api.cpp failed: undeclared inclusion(s) in rule '//mediapipe/examples/desktop/hand_tracking_test:Mediapipe_Hand_Tracking': this rule is missing dependency declarations for the following files included by 'mediapipe/examples/desktop/hand_tracking_test/hand_tracking_api.cpp': 'external/com_google_absl/absl/flags/parse.h' 'external/com_google_absl/absl/flags/internal/parse.h' 'mediapipe/framework/port/parse_text_proto.h'_
> 
> if I add _"//mediapipe/examples/desktop:demo_run_graph_main"_ to BUILD file deps, there ought to be some error
> 
> _ERROR: D:/_longgoodprojects/mediapipe/mediapipe/examples/desktop/hand_tracking_test/BUILD:27:10: Compiling mediapipe/examples/desktop/hand_tracking_test/hand_tracking_detect.cpp failed: undeclared inclusion(s) in rule '//mediapipe/examples/desktop/hand_tracking_test:Mediapipe_Hand_Tracking': this rule is missing dependency declarations for the following files included by 'mediapipe/examples/desktop/hand_tracking_test/hand_tracking_detect.cpp': 'mediapipe/examples/desktop/hand_tracking_test/hand_up_hand_down_detect.h' Target //mediapipe/examples/desktop/hand_tracking_test:Mediapipe_Hand_Tracking failed to build_
> 
> **2. BUILD content** _cc_binary( name = "Mediapipe_Hand_Tracking", srcs = ["hand_tracking_api.h","hand_tracking_api.cpp","hand_tracking_detect.h","hand_tracking_detect.cpp","hand_tracking_data.h","hand_gesture_recognition.h","hand_gesture_recognition.cpp"], linkshared=True, deps = [ "//mediapipe/graphs/hand_tracking:desktop_tflite_calculators", ], )_
> 
> still trying to figure out how to solve it, if I have your support, it would be grateful.

Do you use the BUILD file in my repositories or the BUILD file created by yourself ?
I am puzzled why this file "mediapipe/framework/port/parse_text_proto.h" cannot be found , this file exist in the Mediapipe.
![image](https://user-images.githubusercontent.com/23658564/141218953-0b106bf5-e7e1-4e1d-acef-edc409c5a596.png)

**Comment by HW140701** [comment]
> > Before this can be close exactly, I have ready most of the discussion and you help them to be success kindly. I have complete the action to build execution file, such as HelloWorld, and handtracking are runing through very well.
> > I would like to write down most of my material and build information as follow. **0. build command** bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:\Python37\python.exe" mediapipe/examples/desktop/hand_tracking_test:Mediapipe_Hand_Tracking --verbose_failures
> > **1.The error msg after the building** _D:/_longgoodprojects/mediapipe/mediapipe/examples/desktop/hand_tracking_test/BUILD:27:10: Compiling mediapipe/examples/desktop/hand_tracking_test/hand_tracking_api.cpp failed: undeclared inclusion(s) in rule '//mediapipe/examples/desktop/hand_tracking_test:Mediapipe_Hand_Tracking': this rule is missing dependency declarations for the following files included by 'mediapipe/examples/desktop/hand_tracking_test/hand_tracking_api.cpp': 'external/com_google_absl/absl/flags/parse.h' 'external/com_google_absl/absl/flags/internal/parse.h' 'mediapipe/framework/port/parse_text_proto.h'_
> > if I add _"//mediapipe/examples/desktop:demo_run_graph_main"_ to BUILD file deps, there ought to be some error
> > _ERROR: D:/_longgoodprojects/mediapipe/mediapipe/examples/desktop/hand_tracking_test/BUILD:27:10: Compiling mediapipe/examples/desktop/hand_tracking_test/hand_tracking_detect.cpp failed: undeclared inclusion(s) in rule '//mediapipe/examples/desktop/hand_tracking_test:Mediapipe_Hand_Tracking': this rule is missing dependency declarations for the following files included by 'mediapipe/examples/desktop/hand_tracking_test/hand_tracking_detect.cpp': 'mediapipe/examples/desktop/hand_tracking_test/hand_up_hand_down_detect.h' Target //mediapipe/examples/desktop/hand_tracking_test:Mediapipe_Hand_Tracking failed to build_
> > **2. BUILD content** _cc_binary( name = "Mediapipe_Hand_Tracking", srcs = ["hand_tracking_api.h","hand_tracking_api.cpp","hand_tracking_detect.h","hand_tracking_detect.cpp","hand_tracking_data.h","hand_gesture_recognition.h","hand_gesture_recognition.cpp"], linkshared=True, deps = [ "//mediapipe/graphs/hand_tracking:desktop_tflite_calculators", ], )_
> > still trying to figure out how to solve it, if I have your support, it would be grateful.
> 
> Do you use the BUILD file in my repositories or the BUILD file created by yourself ? I am puzzled why this file "mediapipe/framework/port/parse_text_proto.h" cannot be found , this file exist in the Mediapipe. ![image](https://user-images.githubusercontent.com/23658564/141218953-0b106bf5-e7e1-4e1d-acef-edc409c5a596.png)

From the 19th line of the WORKSPACE file in the Mediapipe repository, the ABSL library will be requested remotely. It is estimated that this error 'external/com_google_absl/absl/flags/parse.h' 'external/com_google_absl/absl/flags/internal/parse.h' may be that the library was not downloaded successfully. Please check the compilation output error carefully to see if there are other errors before this error.

**Comment by longgood** [comment]
Nice to see you help to figure those issue. 
1. Yes, I use the same BUILD file and code from your repositories.
2. "parse_text_proto.h" existed. 
3. But the folder and files under "external" folder are not. this could be the issue you mentioned from the 19th line of the WORKSPACE file in the mediapipe respository. any suggestion for this parts. (I have manually download files and mk folders, though it does not work)
listed as followed is my compile output for reference.
many thanks.
![image](https://user-images.githubusercontent.com/6151892/144559614-ad07eac4-43fb-4cb8-8d06-04ba89495582.png)

**Comment by longgood** [comment]
I found those files are not downloaded.

WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/toolchains/archive/d781e89e2ee797ea7afd0c8391e761616fc5d50d.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/0a8c6996bd6a58eb0e7e2fe049ac67bf663e1950.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/28407b24f04694a1353ffca91248e89bc250eb5b.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
